PROFILE: "dev"
PORT: 8000
SERVER_NAME: "url-generator-1"
DB_USER: "reck"
DB_PASSWORD: "reck"
DB_HOST: "localhost"
DB_PORT: 3306
DB_NAME: "urlshortener"
ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:4000"
REDIS_ADDRESS: "localhost:6379"
REDIS_PASSWORD: ""
TOKEN_RANGE_SIZE: 999
REACT_APP_URL: "http://localhost:3000"

